# Generated by Django 3.2.3 on 2021-05-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='identificationType',
            fields=[
                ('idIdentificationType', models.AutoField(primary_key=True, serialize=False)),
                ('codeIdentificationType', models.CharField(max_length=5)),
                ('descriptionIdentificationType', models.CharField(max_length=50)),
            ],
        ),
    ]
