# Generated by Django 3.2.3 on 2021-05-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdentificationType', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationtype',
            name='codeIdentificationType',
            field=models.CharField(max_length=5, verbose_name='Codigo Tipo Identificacion'),
        ),
        migrations.AlterField(
            model_name='identificationtype',
            name='descriptionIdentificationType',
            field=models.CharField(max_length=50, verbose_name='Descripcion Tipo Identificacion'),
        ),
        migrations.AlterField(
            model_name='identificationtype',
            name='idIdentificationType',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id Interno'),
        ),
    ]
