# Generated by Django 3.2.3 on 2021-05-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('idPerson', models.AutoField(primary_key=True, serialize=False)),
                ('typeId', models.CharField(max_length=20)),
                ('numberId', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=50)),
                ('secondName', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('secondSurname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=150)),
                ('countryOfBirth', models.CharField(max_length=100)),
                ('cityOfBirth', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
    ]
