# Generated by Django 3.2.3 on 2021-05-22 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='numberId',
            new_name='idNumber',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='typeId',
            new_name='idType',
        ),
    ]
