# Generated by Django 3.2.3 on 2021-05-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_auto_20210521_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Direccion Residencia'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cityOfBirth',
            field=models.CharField(max_length=100, verbose_name='Ciudad Nacimiento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='countryOfBirth',
            field=models.CharField(max_length=100, verbose_name='Pais Nacimiento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstName',
            field=models.CharField(max_length=50, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='F', max_length=20, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='idNumber',
            field=models.CharField(max_length=30, verbose_name='Numero Identificación'),
        ),
        migrations.AlterField(
            model_name='person',
            name='idPerson',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id Interno'),
        ),
        migrations.AlterField(
            model_name='person',
            name='idType',
            field=models.CharField(choices=[('CC', 'Cedula'), ('CE', 'Cedula Extranjeria'), ('P', 'Pasaporte'), ('T', 'Tarjeta Identidad'), ('NUI', 'Numero Unico Identificacion')], default='CC', max_length=5, verbose_name='Tipo Identificación'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('U', 'Usuario Sistema'), ('J', 'Juez'), ('DM', 'Demandado'), ('DMT', 'Demandante')], default='DM', max_length=30, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='person',
            name='secondName',
            field=models.CharField(max_length=50, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='person',
            name='secondSurname',
            field=models.CharField(max_length=50, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Primer Apellido'),
        ),
    ]
